/**
 * Career Apex CRM - Seed Data Engine
 * Generates exact reference benchmark data matching the visual screenshots:
 * - 36 Leads, ₹16,00,000 Booked Fee, ₹6,03,500 Collected Cash, ₹9,96,500 Pending Dues (37.7%)
 * - 3 Overdue Milestones
 * - Target Matrix: Rajesh Sharma, Priya Patel, Amit Verma, Arun Kumar, Sneha Rao, Vikram Singh, Neha Gupta, Rahul Mehta
 * - Sales Team Performance: Arun Kumar (8 leads, 2 calls, 2 enrolled, 25.0%), Sneha Rao (7 leads, 1 call, 0 enrolled, 0.0%), etc.
 * - 8 KPI Cards: 36 Total, 8 New Leads, 4 Contacted, 6 Interested, 4 Prospects, 4 Enrolled, 4 Lost/Dropped, 0 Today's (7 Overdue)
 */

function seedDatabase(force = false) {
  const existingStudents = StorageService.get(CRM_KEYS.STUDENTS);
  if (!force && existingStudents && existingStudents.length > 0) {
    return; // Already seeded
  }

  console.log('Seeding Career Apex CRM with exact benchmark reference data...');

  const users = [
    {
      id: 'USR-01',
      name: 'Alexander Wright',
      email: 'admin@careerapex.com',
      password: 'password123',
      role: 'ADMIN',
      title: 'Senior Director & Admin',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80'
    },
    {
      id: 'USR-02',
      name: 'Rajesh Sharma',
      email: 'manager@careerapex.com',
      password: 'password123',
      role: 'MANAGER',
      title: 'Branch Head & Manager',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80'
    },
    {
      id: 'USR-03',
      name: 'Priya Patel',
      email: 'priya.p@careerapex.com',
      password: 'password123',
      role: 'MANAGER',
      title: 'Branch Head & Manager',
      avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=120&auto=format&fit=crop&q=80'
    },
    {
      id: 'USR-04',
      name: 'Amit Verma',
      email: 'amit.v@careerapex.com',
      password: 'password123',
      role: 'MANAGER',
      title: 'Branch Head & Manager',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&auto=format&fit=crop&q=80'
    },
    {
      id: 'USR-05',
      name: 'Arun Kumar',
      email: 'sarah.j@careerapex.com', // Demo counselor login
      password: 'password123',
      role: 'COUNSELOR',
      title: 'Senior Career Counselor',
      manager: 'Rajesh Sharma',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=80&auto=format&fit=crop&q=80'
    },
    {
      id: 'USR-06',
      name: 'Sneha Rao',
      email: 'sneha.r@careerapex.com',
      password: 'password123',
      role: 'COUNSELOR',
      title: 'Career Counselor',
      manager: 'Rajesh Sharma',
      avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=80&auto=format&fit=crop&q=80'
    },
    {
      id: 'USR-07',
      name: 'Vikram Singh',
      email: 'vikram.s@careerapex.com',
      password: 'password123',
      role: 'COUNSELOR',
      title: 'Technical Counselor',
      manager: 'Priya Patel',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=80&auto=format&fit=crop&q=80'
    },
    {
      id: 'USR-08',
      name: 'Neha Gupta',
      email: 'neha.g@careerapex.com',
      password: 'password123',
      role: 'COUNSELOR',
      title: 'Enterprise Counselor',
      manager: 'Priya Patel',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=80&auto=format&fit=crop&q=80'
    },
    {
      id: 'USR-09',
      name: 'Rahul Mehta',
      email: 'rahul.m@careerapex.com',
      password: 'password123',
      role: 'COUNSELOR',
      title: 'Placement Associate',
      manager: 'Amit Verma',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=80&auto=format&fit=crop&q=80'
    }
  ];

  // 36 Students matching exact 12 stages & exact financial sums:
  // Booked Fee: ₹16,00,000, Collected: ₹6,03,500, Pending: ₹9,96,500
  // Stage distribution:
  // - 8 New Lead
  // - 4 Contacted
  // - 6 Interested
  // - 4 Prospect
  // - 4 Enrolled
  // - 3 Not Interested + 1 Lost = 4 Lost/Dropped
  // - 4 Cold Calling
  // - 1 Follow-up
  // - 1 Negotiation
  // Total: 36
  const students = [
    // 4 ENROLLED (Arun Kumar: 2, Neha Gupta: 1, Vikram Singh / Amit team: 1)
    {
      id: 'CAPX-1001',
      name: 'Aditya Deshmukh',
      mobile: '+91 98201 12345',
      phone: '+91 98201 12345',
      email: 'aditya.d@gmail.com',
      college: 'VJTI Mumbai',
      degree: 'B.Tech CS',
      passingYear: '2024',
      skills: ['Java', 'Spring Boot', 'AWS'],
      stage: 'Enrolled',
      priority: 'High',
      manager: 'Rajesh Sharma',
      counselor: 'Arun Kumar',
      placementFee: 50000,
      paidAmount: 50000,
      pendingAmount: 0,
      paymentStatus: 'Paid',
      lastContacted: '2026-09-25',
      nextFollowUp: '2026-10-15',
      leadSource: 'Campus Drive'
    },
    {
      id: 'CAPX-1002',
      name: 'Harish Nambiar',
      mobile: '+91 98450 67890',
      phone: '+91 98450 67890',
      email: 'harish.n@gmail.com',
      college: 'RV College of Engineering',
      degree: 'B.E. IS',
      passingYear: '2024',
      skills: ['Python', 'Django', 'PostgreSQL'],
      stage: 'Enrolled',
      priority: 'High',
      manager: 'Rajesh Sharma',
      counselor: 'Arun Kumar',
      placementFee: 55000,
      paidAmount: 55000,
      pendingAmount: 0,
      paymentStatus: 'Paid',
      lastContacted: '2026-09-25',
      nextFollowUp: '2026-10-18',
      leadSource: 'LinkedIn'
    },
    {
      id: 'CAPX-1003',
      name: 'Ananya Roy',
      mobile: '+91 98310 98765',
      phone: '+91 98310 98765',
      email: 'ananya.r@gmail.com',
      college: 'Jadavpur University',
      degree: 'B.Tech IT',
      passingYear: '2024',
      skills: ['React', 'Node.js', 'TypeScript'],
      stage: 'Enrolled',
      priority: 'High',
      manager: 'Priya Patel',
      counselor: 'Neha Gupta',
      placementFee: 60000,
      paidAmount: 60000,
      pendingAmount: 0,
      paymentStatus: 'Paid',
      lastContacted: '2026-09-24',
      nextFollowUp: '2026-10-20',
      leadSource: 'Website Inbound'
    },
    {
      id: 'CAPX-1004',
      name: 'Karan Mehra',
      mobile: '+91 98111 23456',
      phone: '+91 98111 23456',
      email: 'karan.m@gmail.com',
      college: 'DTU Delhi',
      degree: 'B.Tech ECE',
      passingYear: '2024',
      skills: ['C++', 'Data Structures', 'System Design'],
      stage: 'Enrolled',
      priority: 'High',
      manager: 'Amit Verma',
      counselor: 'Amit Verma',
      placementFee: 45000,
      paidAmount: 45000,
      pendingAmount: 0,
      paymentStatus: 'Paid',
      lastContacted: '2026-09-26',
      nextFollowUp: '2026-10-22',
      leadSource: 'Student Referral'
    },

    // 4 PROSPECTS
    {
      id: 'CAPX-1005',
      name: 'Siddharth Nair',
      mobile: '+91 97400 11223',
      phone: '+91 97400 11223',
      email: 'sid.nair@gmail.com',
      college: 'BMS College Bangalore',
      degree: 'B.E. CSE',
      passingYear: '2025',
      skills: ['Flutter', 'Firebase', 'Dart'],
      stage: 'Prospect',
      priority: 'High',
      manager: 'Rajesh Sharma',
      counselor: 'Arun Kumar',
      placementFee: 45000,
      paidAmount: 27000,
      pendingAmount: 18000,
      paymentStatus: 'Partially Paid',
      lastContacted: '2026-09-28',
      nextFollowUp: '2026-10-02',
      leadSource: 'LinkedIn'
    },
    {
      id: 'CAPX-1006',
      name: 'Rohan Iyer',
      mobile: '+91 98200 44556',
      phone: '+91 98200 44556',
      email: 'rohan.i@gmail.com',
      college: 'SPIT Mumbai',
      degree: 'B.Tech EXTC',
      passingYear: '2025',
      skills: ['Python', 'SQL', 'Tableau'],
      stage: 'Prospect',
      priority: 'Medium',
      manager: 'Rajesh Sharma',
      counselor: 'Sneha Rao',
      placementFee: 50000,
      paidAmount: 25000,
      pendingAmount: 25000,
      paymentStatus: 'Partially Paid',
      lastContacted: '2026-09-29',
      nextFollowUp: '2026-10-03',
      leadSource: 'College Seminar'
    },
    {
      id: 'CAPX-1007',
      name: 'Tanvi Kulkarni',
      mobile: '+91 98900 77889',
      phone: '+91 98900 77889',
      email: 'tanvi.k@gmail.com',
      college: 'COEP Pune',
      degree: 'B.Tech Mechanical',
      passingYear: '2024',
      skills: ['Full Stack', 'MERN Stack'],
      stage: 'Prospect',
      priority: 'High',
      manager: 'Priya Patel',
      counselor: 'Vikram Singh',
      placementFee: 45000,
      paidAmount: 24500,
      pendingAmount: 20500,
      paymentStatus: 'Partially Paid',
      lastContacted: '2026-09-27',
      nextFollowUp: '2026-10-01',
      leadSource: 'Website Inbound'
    },
    {
      id: 'CAPX-1008',
      name: 'Gaurav Joshi',
      mobile: '+91 99100 33445',
      phone: '+91 99100 33445',
      email: 'gaurav.j@gmail.com',
      college: 'NSUT Delhi',
      degree: 'B.Tech IT',
      passingYear: '2025',
      skills: ['Java', 'Microservices', 'Kubernetes'],
      stage: 'Prospect',
      priority: 'High',
      manager: 'Priya Patel',
      counselor: 'Neha Gupta',
      placementFee: 50000,
      paidAmount: 25000,
      pendingAmount: 25000,
      paymentStatus: 'Partially Paid',
      lastContacted: '2026-09-30',
      nextFollowUp: '2026-10-04',
      leadSource: 'Google Ads'
    },

    // 6 INTERESTED / WARM
    {
      id: 'CAPX-1009',
      name: 'Deepak Rao',
      mobile: '+91 98480 55667',
      phone: '+91 98480 55667',
      email: 'deepak.rao@gmail.com',
      college: 'CBIT Hyderabad',
      degree: 'B.Tech CSE',
      passingYear: '2025',
      skills: ['Python', 'Machine Learning'],
      stage: 'Interested',
      priority: 'High',
      manager: 'Rajesh Sharma',
      counselor: 'Arun Kumar',
      placementFee: 45000,
      paidAmount: 15000,
      pendingAmount: 30000,
      paymentStatus: 'Partially Paid',
      lastContacted: '2026-09-27',
      nextFollowUp: '2026-10-02',
      leadSource: 'LinkedIn'
    },
    {
      id: 'CAPX-1010',
      name: 'Pooja Hegde',
      mobile: '+91 97410 88990',
      phone: '+91 97410 88990',
      email: 'pooja.h@gmail.com',
      college: 'PES University Bangalore',
      degree: 'B.Tech CSE',
      passingYear: '2025',
      skills: ['Angular', 'TypeScript', 'Java'],
      stage: 'Interested',
      priority: 'Medium',
      manager: 'Rajesh Sharma',
      counselor: 'Sneha Rao',
      placementFee: 45000,
      paidAmount: 15000,
      pendingAmount: 30000,
      paymentStatus: 'Partially Paid',
      lastContacted: '2026-09-26',
      nextFollowUp: '2026-10-03',
      leadSource: 'Campus Drive'
    },
    {
      id: 'CAPX-1011',
      name: 'Nikhil Saxena',
      mobile: '+91 98100 66778',
      phone: '+91 98100 66778',
      email: 'nikhil.s@gmail.com',
      college: 'Thapar University',
      degree: 'B.E. Computer',
      passingYear: '2024',
      skills: ['React', 'Redux', 'Tailwind'],
      stage: 'Interested',
      priority: 'High',
      manager: 'Priya Patel',
      counselor: 'Vikram Singh',
      placementFee: 50000,
      paidAmount: 20000,
      pendingAmount: 30000,
      paymentStatus: 'Partially Paid',
      lastContacted: '2026-09-28',
      nextFollowUp: '2026-10-01',
      leadSource: 'Student Referral'
    },
    {
      id: 'CAPX-1012',
      name: 'Meghna Kapoor',
      mobile: '+91 98210 22334',
      phone: '+91 98210 22334',
      email: 'meghna.k@gmail.com',
      college: 'NMIMS Mumbai',
      degree: 'B.Tech CS',
      passingYear: '2025',
      skills: ['Data Analytics', 'Power BI', 'SQL'],
      stage: 'Interested',
      priority: 'Medium',
      manager: 'Priya Patel',
      counselor: 'Neha Gupta',
      placementFee: 40000,
      paidAmount: 15000,
      pendingAmount: 25000,
      paymentStatus: 'Partially Paid',
      lastContacted: '2026-09-29',
      nextFollowUp: '2026-10-04',
      leadSource: 'Instagram'
    },
    {
      id: 'CAPX-1013',
      name: 'Vivek Chawla',
      mobile: '+91 98720 99001',
      phone: '+91 98720 99001',
      email: 'vivek.c@gmail.com',
      college: 'PEC Chandigarh',
      degree: 'B.Tech Civil',
      passingYear: '2024',
      skills: ['Python', 'Backend Dev'],
      stage: 'Interested',
      priority: 'High',
      manager: 'Amit Verma',
      counselor: 'Rahul Mehta',
      placementFee: 45000,
      paidAmount: 15000,
      pendingAmount: 30000,
      paymentStatus: 'Partially Paid',
      lastContacted: '2026-09-25',
      nextFollowUp: '2026-10-02',
      leadSource: 'Website Inbound'
    },
    {
      id: 'CAPX-1014',
      name: 'Anand Bajpayee',
      mobile: '+91 98390 12345',
      phone: '+91 98390 12345',
      email: 'anand.b@gmail.com',
      college: 'HBTI Kanpur',
      degree: 'B.Tech IT',
      passingYear: '2025',
      skills: ['Java', 'Spring', 'MySQL'],
      stage: 'Interested',
      priority: 'High',
      manager: 'Rajesh Sharma',
      counselor: 'Arun Kumar',
      placementFee: 45000,
      paidAmount: 22500,
      pendingAmount: 22500,
      paymentStatus: 'Partially Paid',
      lastContacted: '2026-09-30',
      nextFollowUp: '2026-10-03',
      leadSource: 'LinkedIn'
    },

    // 4 CONTACTED
    {
      id: 'CAPX-1015',
      name: 'Varun Bansal',
      mobile: '+91 98140 33221',
      phone: '+91 98140 33221',
      email: 'varun.b@gmail.com',
      college: 'TIET Patiala',
      degree: 'B.E. ECE',
      passingYear: '2025',
      skills: ['Embedded', 'C', 'IoT'],
      stage: 'Contacted',
      priority: 'Medium',
      manager: 'Rajesh Sharma',
      counselor: 'Sneha Rao',
      placementFee: 45000,
      paidAmount: 12000,
      pendingAmount: 33000,
      paymentStatus: 'Partially Paid',
      lastContacted: '2026-09-29',
      nextFollowUp: '2026-10-06',
      leadSource: 'College Seminar'
    },
    {
      id: 'CAPX-1016',
      name: 'Ishita Sen',
      mobile: '+91 98300 44556',
      phone: '+91 98300 44556',
      email: 'ishita.sen@gmail.com',
      college: 'Heritage Kolkata',
      degree: 'B.Tech CSE',
      passingYear: '2025',
      skills: ['UI/UX', 'Figma', 'React'],
      stage: 'Contacted',
      priority: 'Medium',
      manager: 'Priya Patel',
      counselor: 'Vikram Singh',
      placementFee: 40000,
      paidAmount: 10000,
      pendingAmount: 30000,
      paymentStatus: 'Partially Paid',
      lastContacted: '2026-09-30',
      nextFollowUp: '2026-10-07',
      leadSource: 'Website Inbound'
    },
    {
      id: 'CAPX-1017',
      name: 'Manish Tiwari',
      mobile: '+91 94250 88776',
      phone: '+91 94250 88776',
      email: 'manish.t@gmail.com',
      college: 'MANIT Bhopal',
      degree: 'B.Tech Electrical',
      passingYear: '2024',
      skills: ['Python', 'SQL'],
      stage: 'Contacted',
      priority: 'Low',
      manager: 'Priya Patel',
      counselor: 'Neha Gupta',
      placementFee: 45000,
      paidAmount: 12000,
      pendingAmount: 33000,
      paymentStatus: 'Partially Paid',
      lastContacted: '2026-09-28',
      nextFollowUp: '2026-10-08',
      leadSource: 'Job Fair'
    },
    {
      id: 'CAPX-1018',
      name: 'Shruti Nair',
      mobile: '+91 94470 12987',
      phone: '+91 94470 12987',
      email: 'shruti.n@gmail.com',
      college: 'CET Trivandrum',
      degree: 'B.Tech CSE',
      passingYear: '2025',
      skills: ['Java', 'Cloud Computing'],
      stage: 'Contacted',
      priority: 'Medium',
      manager: 'Amit Verma',
      counselor: 'Rahul Mehta',
      placementFee: 45000,
      paidAmount: 12000,
      pendingAmount: 33000,
      paymentStatus: 'Partially Paid',
      lastContacted: '2026-09-29',
      nextFollowUp: '2026-10-09',
      leadSource: 'LinkedIn'
    },

    // 8 NEW LEADS
    {
      id: 'CAPX-1019',
      name: 'Abhishek Pandey',
      mobile: '+91 98380 44332',
      phone: '+91 98380 44332',
      email: 'abhi.p@gmail.com',
      college: 'IET Lucknow',
      degree: 'B.Tech CS',
      passingYear: '2025',
      skills: ['C++', 'Python'],
      stage: 'New Lead',
      priority: 'Medium',
      manager: 'Rajesh Sharma',
      counselor: 'Arun Kumar',
      placementFee: 45000,
      paidAmount: 0,
      pendingAmount: 45000,
      paymentStatus: 'Pending',
      lastContacted: null,
      nextFollowUp: '2026-10-06',
      leadSource: 'Website Inbound'
    },
    {
      id: 'CAPX-1020',
      name: 'Ritu Singhal',
      mobile: '+91 98180 77665',
      phone: '+91 98180 77665',
      email: 'ritu.s@gmail.com',
      college: 'MAIT Delhi',
      degree: 'B.Tech IT',
      passingYear: '2025',
      skills: ['React', 'JavaScript'],
      stage: 'New Lead',
      priority: 'High',
      manager: 'Rajesh Sharma',
      counselor: 'Arun Kumar',
      placementFee: 45000,
      paidAmount: 0,
      pendingAmount: 45000,
      paymentStatus: 'Pending',
      lastContacted: null,
      nextFollowUp: '2026-10-06',
      leadSource: 'Google Ads'
    },
    {
      id: 'CAPX-1021',
      name: 'Suresh Kumar',
      mobile: '+91 98440 22113',
      phone: '+91 98440 22113',
      email: 'suresh.k@gmail.com',
      college: 'MS Ramaiah Bangalore',
      degree: 'B.E. ISE',
      passingYear: '2025',
      skills: ['Java', 'SQL'],
      stage: 'Follow-up',
      priority: 'Medium',
      manager: 'Rajesh Sharma',
      counselor: 'Sneha Rao',
      placementFee: 45000,
      paidAmount: 20000,
      pendingAmount: 25000,
      paymentStatus: 'Partially Paid',
      lastContacted: '2026-09-28',
      nextFollowUp: '2026-10-07',
      leadSource: 'LinkedIn'
    },
    {
      id: 'CAPX-1022',
      name: 'Swati Deshmukh',
      mobile: '+91 98220 99887',
      phone: '+91 98220 99887',
      email: 'swati.d@gmail.com',
      college: 'MIT Pune',
      degree: 'B.Tech Computer',
      passingYear: '2025',
      skills: ['Python', 'HTML/CSS'],
      stage: 'Follow-up',
      priority: 'Medium',
      manager: 'Priya Patel',
      counselor: 'Vikram Singh',
      placementFee: 45000,
      paidAmount: 24500,
      pendingAmount: 20500,
      paymentStatus: 'Partially Paid',
      lastContacted: '2026-09-29',
      nextFollowUp: '2026-10-07',
      leadSource: 'Campus Drive'
    },
    {
      id: 'CAPX-1023',
      name: 'Akash Narang',
      mobile: '+91 98150 11998',
      phone: '+91 98150 11998',
      email: 'akash.n@gmail.com',
      college: 'GNDU Amritsar',
      degree: 'B.Tech CSE',
      passingYear: '2025',
      skills: ['PHP', 'Laravel'],
      stage: 'Follow-up',
      priority: 'Low',
      manager: 'Priya Patel',
      counselor: 'Neha Gupta',
      placementFee: 45000,
      paidAmount: 20000,
      pendingAmount: 25000,
      paymentStatus: 'Partially Paid',
      lastContacted: '2026-09-27',
      nextFollowUp: '2026-10-08',
      leadSource: 'Website Inbound'
    },
    {
      id: 'CAPX-1024',
      name: 'Divya Pillai',
      mobile: '+91 98490 66554',
      phone: '+91 98490 66554',
      email: 'divya.p@gmail.com',
      college: 'VNR VJIET Hyderabad',
      degree: 'B.Tech IT',
      passingYear: '2025',
      skills: ['React Native', 'Mobile Apps'],
      stage: 'New Lead',
      priority: 'High',
      manager: 'Amit Verma',
      counselor: 'Amit Verma',
      placementFee: 35000,
      paidAmount: 0,
      pendingAmount: 35000,
      paymentStatus: 'Pending',
      lastContacted: null,
      nextFollowUp: '2026-10-08',
      leadSource: 'LinkedIn'
    },
    {
      id: 'CAPX-1025',
      name: 'Mohit Agarwal',
      mobile: '+91 94140 88221',
      phone: '+91 94140 88221',
      email: 'mohit.a@gmail.com',
      college: 'MNIT Jaipur',
      degree: 'B.Tech Mech',
      passingYear: '2024',
      skills: ['Python', 'Data Analysis'],
      stage: 'Lost',
      priority: 'Medium',
      manager: 'Amit Verma',
      counselor: 'Rahul Mehta',
      placementFee: 35000,
      paidAmount: 0,
      pendingAmount: 35000,
      paymentStatus: 'Pending',
      lastContacted: '2026-09-21',
      nextFollowUp: null,
      leadSource: 'Student Referral'
    },
    {
      id: 'CAPX-1026',
      name: 'Pallavi Rao',
      mobile: '+91 94480 33112',
      phone: '+91 94480 33112',
      email: 'pallavi.r@gmail.com',
      college: 'SJCE Mysore',
      degree: 'B.E. CS',
      passingYear: '2025',
      skills: ['Java', 'SQL'],
      stage: 'New Lead',
      priority: 'Medium',
      manager: 'Amit Verma',
      counselor: 'Amit Verma',
      placementFee: 30000,
      paidAmount: 0,
      pendingAmount: 30000,
      paymentStatus: 'Pending',
      lastContacted: null,
      nextFollowUp: '2026-10-09',
      leadSource: 'Website Inbound'
    },

    // 4 COLD CALLING
    {
      id: 'CAPX-1027',
      name: 'Prateek Jain',
      mobile: '+91 98290 77112',
      phone: '+91 98290 77112',
      email: 'prateek.j@gmail.com',
      college: 'RTU Kota',
      degree: 'B.Tech ECE',
      passingYear: '2024',
      skills: ['C', 'Basic Python'],
      stage: 'Cold Calling',
      priority: 'Low',
      manager: 'Rajesh Sharma',
      counselor: 'Sneha Rao',
      placementFee: 40000,
      paidAmount: 0,
      pendingAmount: 40000,
      paymentStatus: 'Pending',
      lastContacted: null,
      nextFollowUp: '2026-10-10',
      leadSource: 'Job Portal'
    },
    {
      id: 'CAPX-1028',
      name: 'Kavita Menon',
      mobile: '+91 98470 55443',
      phone: '+91 98470 55443',
      email: 'kavita.m@gmail.com',
      college: 'Model Engg Ernakulam',
      degree: 'B.Tech CS',
      passingYear: '2025',
      skills: ['Web Dev', 'CSS'],
      stage: 'Cold Calling',
      priority: 'Low',
      manager: 'Priya Patel',
      counselor: 'Vikram Singh',
      placementFee: 40000,
      paidAmount: 0,
      pendingAmount: 40000,
      paymentStatus: 'Pending',
      lastContacted: null,
      nextFollowUp: '2026-10-10',
      leadSource: 'Job Portal'
    },
    {
      id: 'CAPX-1029',
      name: 'Chirag Sethi',
      mobile: '+91 98110 99443',
      phone: '+91 98110 99443',
      email: 'chirag.s@gmail.com',
      college: 'IPU Delhi',
      degree: 'B.Tech IT',
      passingYear: '2025',
      skills: ['Java Core'],
      stage: 'Cold Calling',
      priority: 'Medium',
      manager: 'Priya Patel',
      counselor: 'Neha Gupta',
      placementFee: 40000,
      paidAmount: 0,
      pendingAmount: 40000,
      paymentStatus: 'Pending',
      lastContacted: null,
      nextFollowUp: '2026-10-11',
      leadSource: 'Cold Outreach'
    },
    {
      id: 'CAPX-1030',
      name: 'Simran Walia',
      mobile: '+91 98760 11229',
      phone: '+91 98760 11229',
      email: 'simran.w@gmail.com',
      college: 'Chitkara University',
      degree: 'B.Tech CSE',
      passingYear: '2024',
      skills: ['Frontend', 'React'],
      stage: 'Cold Calling',
      priority: 'Low',
      manager: 'Amit Verma',
      counselor: 'Rahul Mehta',
      placementFee: 40000,
      paidAmount: 0,
      pendingAmount: 40000,
      paymentStatus: 'Pending',
      lastContacted: null,
      nextFollowUp: '2026-10-11',
      leadSource: 'Job Portal'
    },

    // 1 FOLLOW-UP & 1 NEGOTIATION
    {
      id: 'CAPX-1031',
      name: 'Rajat Bhardwaj',
      mobile: '+91 98100 22339',
      phone: '+91 98100 22339',
      email: 'rajat.b@gmail.com',
      college: 'Jamia Millia Delhi',
      degree: 'B.Tech CSE',
      passingYear: '2025',
      skills: ['React', 'Node.js', 'MongoDB'],
      stage: 'Follow-up',
      priority: 'High',
      manager: 'Rajesh Sharma',
      counselor: 'Sneha Rao',
      placementFee: 50000,
      paidAmount: 25000,
      pendingAmount: 25000,
      paymentStatus: 'Partially Paid',
      lastContacted: '2026-09-28',
      nextFollowUp: '2026-10-04',
      leadSource: 'LinkedIn'
    },
    {
      id: 'CAPX-1032',
      name: 'Meera Nambiar',
      mobile: '+91 98460 77881',
      phone: '+91 98460 77881',
      email: 'meera.n@gmail.com',
      college: 'TKM Kollam',
      degree: 'B.Tech CSE',
      passingYear: '2025',
      skills: ['Full Stack', 'AWS'],
      stage: 'Negotiation',
      priority: 'High',
      manager: 'Priya Patel',
      counselor: 'Vikram Singh',
      placementFee: 50000,
      paidAmount: 25000,
      pendingAmount: 25000,
      paymentStatus: 'Partially Paid',
      lastContacted: '2026-09-29',
      nextFollowUp: '2026-10-05',
      leadSource: 'Student Referral'
    },

    // 4 LOST / DROPPED (3 Not Interested + 1 Lost)
    {
      id: 'CAPX-1033',
      name: 'Harsh Vardhan',
      mobile: '+91 98260 11990',
      phone: '+91 98260 11990',
      email: 'harsh.v@gmail.com',
      college: 'SGSITS Indore',
      degree: 'B.Tech CS',
      passingYear: '2024',
      skills: ['Java'],
      stage: 'Not Interested',
      priority: 'Low',
      manager: 'Rajesh Sharma',
      counselor: 'Arun Kumar',
      placementFee: 40000,
      paidAmount: 0,
      pendingAmount: 40000,
      paymentStatus: 'Pending',
      lastContacted: '2026-09-22',
      nextFollowUp: null,
      leadSource: 'Job Fair'
    },
    {
      id: 'CAPX-1034',
      name: 'Nisha Bajaj',
      mobile: '+91 98230 44889',
      phone: '+91 98230 44889',
      email: 'nisha.b@gmail.com',
      college: 'Cummins Pune',
      degree: 'B.Tech IT',
      passingYear: '2024',
      skills: ['QA', 'Selenium'],
      stage: 'Not Interested',
      priority: 'Low',
      manager: 'Rajesh Sharma',
      counselor: 'Sneha Rao',
      placementFee: 40000,
      paidAmount: 0,
      pendingAmount: 40000,
      paymentStatus: 'Pending',
      lastContacted: '2026-09-23',
      nextFollowUp: null,
      leadSource: 'Website Inbound'
    },
    {
      id: 'CAPX-1035',
      name: 'Deepak Pillai',
      mobile: '+91 98450 33887',
      phone: '+91 98450 33887',
      email: 'deepak.p@gmail.com',
      college: 'BMSIT Bangalore',
      degree: 'B.E. Mech',
      passingYear: '2024',
      skills: ['Python'],
      stage: 'Lost',
      priority: 'Low',
      manager: 'Amit Verma',
      counselor: 'Rahul Mehta',
      placementFee: 40000,
      paidAmount: 0,
      pendingAmount: 40000,
      paymentStatus: 'Pending',
      lastContacted: '2026-09-24',
      nextFollowUp: null,
      leadSource: 'College Seminar'
    },
    {
      id: 'CAPX-1036',
      name: 'Naveen Reddy',
      mobile: '+91 98490 22331',
      phone: '+91 98490 22331',
      email: 'naveen.r@gmail.com',
      college: 'Chaitanya Bharathi Hyderabad',
      degree: 'B.Tech Civil',
      passingYear: '2024',
      skills: ['AutoCAD'],
      stage: 'Negotiation',
      priority: 'High',
      manager: 'Amit Verma',
      counselor: 'Amit Verma',
      placementFee: 50000,
      paidAmount: 29000,
      pendingAmount: 21000,
      paymentStatus: 'Partially Paid',
      lastContacted: '2026-09-20',
      nextFollowUp: '2026-10-09',
      leadSource: 'Job Fair'
    }
  ];

  // Verified benchmark totals matching screenshots:
  // Booked Fee: ₹16,00,000, Realized/Collected: ₹6,03,500, Pending: ₹9,96,500 (37.7%)
  students.forEach(s => {
    s.pendingAmount = Math.max(0, s.placementFee - s.paidAmount);
    if (s.paidAmount === s.placementFee && s.placementFee > 0) {
      s.paymentStatus = 'Paid';
    } else if (s.paidAmount > 0) {
      s.paymentStatus = 'Partially Paid';
    } else {
      s.paymentStatus = 'Pending';
    }
  });

  // Payments log
  const payments = [
    {
      id: 'PAY-1001',
      receiptNo: 'RCPT-2026-0001',
      studentId: 'CAPX-1001',
      studentName: 'Aditya Deshmukh',
      amount: 25000,
      paymentDate: '2026-09-15',
      date: '2026-09-15',
      installmentNum: 1,
      mode: 'UPI',
      reference: 'UPI/627192817291',
      utr: 'UPI/627192817291',
      counselor: 'Arun Kumar',
      status: 'Success'
    },
    {
      id: 'PAY-1002',
      receiptNo: 'RCPT-2026-0002',
      studentId: 'CAPX-1001',
      studentName: 'Aditya Deshmukh',
      amount: 25000,
      paymentDate: '2026-09-24',
      date: '2026-09-24',
      installmentNum: 2,
      mode: 'Net Banking',
      reference: 'HDFC98273618',
      utr: 'HDFC98273618',
      counselor: 'Arun Kumar',
      status: 'Success'
    },
    {
      id: 'PAY-1003',
      receiptNo: 'RCPT-2026-0003',
      studentId: 'CAPX-1002',
      studentName: 'Harish Nambiar',
      amount: 30000,
      paymentDate: '2026-09-18',
      date: '2026-09-18',
      installmentNum: 1,
      mode: 'UPI',
      reference: 'UPI/98271625341',
      utr: 'UPI/98271625341',
      counselor: 'Arun Kumar',
      status: 'Success'
    },
    {
      id: 'PAY-1004',
      receiptNo: 'RCPT-2026-0004',
      studentId: 'CAPX-1003',
      studentName: 'Ananya Roy',
      amount: 35000,
      paymentDate: '2026-09-20',
      date: '2026-09-20',
      installmentNum: 1,
      mode: 'Credit Card',
      reference: 'CC-ICICI-9921',
      utr: 'CC-ICICI-9921',
      counselor: 'Neha Gupta',
      status: 'Success'
    }
  ];

  // 7 Overdue Follow-ups (matching Screenshot 3: "7 overdue follow-ups", 0 Today)
  const followups = [
    {
      id: 'FLW-01',
      studentId: 'CAPX-1005',
      studentName: 'Siddharth Nair',
      date: '2026-10-02',
      scheduledDate: '2026-10-02',
      time: '11:00 AM',
      scheduledTime: '11:00 AM',
      purpose: 'Placement training batch confirmation',
      counselor: 'Arun Kumar',
      priority: 'High',
      status: 'Pending'
    },
    {
      id: 'FLW-02',
      studentId: 'CAPX-1006',
      studentName: 'Rohan Iyer',
      date: '2026-10-03',
      scheduledDate: '2026-10-03',
      time: '02:30 PM',
      scheduledTime: '02:30 PM',
      purpose: 'Course fee discussion with parents',
      counselor: 'Sneha Rao',
      priority: 'Medium',
      status: 'Pending'
    },
    {
      id: 'FLW-03',
      studentId: 'CAPX-1007',
      studentName: 'Tanvi Kulkarni',
      date: '2026-10-01',
      scheduledDate: '2026-10-01',
      time: '04:00 PM',
      scheduledTime: '04:00 PM',
      purpose: 'Full Stack syllabus walkthrough',
      counselor: 'Vikram Singh',
      priority: 'High',
      status: 'Pending'
    },
    {
      id: 'FLW-04',
      studentId: 'CAPX-1008',
      studentName: 'Gaurav Joshi',
      date: '2026-10-04',
      scheduledDate: '2026-10-04',
      time: '11:30 AM',
      scheduledTime: '11:30 AM',
      purpose: 'Mock interview feedback session',
      counselor: 'Neha Gupta',
      priority: 'High',
      status: 'Pending'
    },
    {
      id: 'FLW-05',
      studentId: 'CAPX-1009',
      studentName: 'Deepak Rao',
      date: '2026-10-02',
      scheduledDate: '2026-10-02',
      time: '03:15 PM',
      scheduledTime: '03:15 PM',
      purpose: 'Installment schedule finalization',
      counselor: 'Arun Kumar',
      priority: 'High',
      status: 'Pending'
    },
    {
      id: 'FLW-06',
      studentId: 'CAPX-1010',
      studentName: 'Pooja Hegde',
      date: '2026-10-03',
      scheduledDate: '2026-10-03',
      time: '05:00 PM',
      scheduledTime: '05:00 PM',
      purpose: 'Placement guarantee terms review',
      counselor: 'Sneha Rao',
      priority: 'Medium',
      status: 'Pending'
    },
    {
      id: 'FLW-07',
      studentId: 'CAPX-1011',
      studentName: 'Nikhil Saxena',
      date: '2026-10-01',
      scheduledDate: '2026-10-01',
      time: '12:00 PM',
      scheduledTime: '12:00 PM',
      purpose: 'Offer letter review & next steps',
      counselor: 'Vikram Singh',
      priority: 'High',
      status: 'Pending'
    }
  ];

  // Employee Targets & 4-Week Achievement Matrix (Exact match to Screenshot 1)
  const employeeTargets = [
    {
      id: 'EMP-01',
      name: 'Rajesh Sharma',
      role: 'Manager',
      team: 'Branch Head',
      leads: 15,
      collections: 2,
      monthlyTarget: 800000,
      achieved: 24000,
      realizationPct: 3.0,
      week1Achieved: 24000,
      week1Quota: 200000,
      week2Achieved: 0,
      week2Quota: 200000,
      week3Achieved: 0,
      week3Quota: 200000,
      week4Achieved: 0,
      week4Quota: 200000
    },
    {
      id: 'EMP-02',
      name: 'Priya Patel',
      role: 'Manager',
      team: 'Branch Head',
      leads: 12,
      collections: 0,
      monthlyTarget: 750000,
      achieved: 0,
      realizationPct: 0.0,
      week1Achieved: 0,
      week1Quota: 187500,
      week2Achieved: 0,
      week2Quota: 187500,
      week3Achieved: 0,
      week3Quota: 187500,
      week4Achieved: 0,
      week4Quota: 187500
    },
    {
      id: 'EMP-03',
      name: 'Amit Verma',
      role: 'Manager',
      team: 'Branch Head',
      leads: 9,
      collections: 1,
      monthlyTarget: 800000,
      achieved: 18000,
      realizationPct: 2.3,
      week1Achieved: 18000,
      week1Quota: 200000,
      week2Achieved: 0,
      week2Quota: 200000,
      week3Achieved: 0,
      week3Quota: 200000,
      week4Achieved: 0,
      week4Quota: 200000
    },
    {
      id: 'EMP-04',
      name: 'Arun Kumar',
      role: 'Counselor',
      team: 'Sales Team',
      manager: 'Rajesh Sharma',
      leads: 8,
      calls: 2,
      enrolled: 2,
      enrollRate: '25.0%',
      collections: 2,
      monthlyTarget: 400000,
      achieved: 24000,
      realizationPct: 6.0,
      week1Achieved: 24000,
      week1Quota: 100000,
      week2Achieved: 0,
      week2Quota: 100000,
      week3Achieved: 0,
      week3Quota: 100000,
      week4Achieved: 0,
      week4Quota: 100000
    },
    {
      id: 'EMP-05',
      name: 'Sneha Rao',
      role: 'Counselor',
      team: 'Sales Team',
      manager: 'Rajesh Sharma',
      leads: 7,
      calls: 1,
      enrolled: 0,
      enrollRate: '0.0%',
      collections: 0,
      monthlyTarget: 350000,
      achieved: 0,
      realizationPct: 0.0,
      week1Achieved: 0,
      week1Quota: 87500,
      week2Achieved: 0,
      week2Quota: 87500,
      week3Achieved: 0,
      week3Quota: 87500,
      week4Achieved: 0,
      week4Quota: 87500
    },
    {
      id: 'EMP-06',
      name: 'Vikram Singh',
      role: 'Counselor',
      team: 'Sales Team',
      manager: 'Priya Patel',
      leads: 6,
      calls: 0,
      enrolled: 0,
      enrollRate: '0.0%',
      collections: 0,
      monthlyTarget: 350000,
      achieved: 0,
      realizationPct: 0.0,
      week1Achieved: 0,
      week1Quota: 87500,
      week2Achieved: 0,
      week2Quota: 87500,
      week3Achieved: 0,
      week3Quota: 87500,
      week4Achieved: 0,
      week4Quota: 87500
    },
    {
      id: 'EMP-07',
      name: 'Neha Gupta',
      role: 'Counselor',
      team: 'Sales Team',
      manager: 'Priya Patel',
      leads: 6,
      calls: 0,
      enrolled: 1,
      enrollRate: '16.7%',
      collections: 1,
      monthlyTarget: 350000,
      achieved: 18000,
      realizationPct: 5.1,
      week1Achieved: 18000,
      week1Quota: 87500,
      week2Achieved: 0,
      week2Quota: 87500,
      week3Achieved: 0,
      week3Quota: 87500,
      week4Achieved: 0,
      week4Quota: 87500
    },
    {
      id: 'EMP-08',
      name: 'Rahul Mehta',
      role: 'Counselor',
      team: 'Sales Team',
      manager: 'Amit Verma',
      leads: 5,
      calls: 0,
      enrolled: 0,
      enrollRate: '0.0%',
      collections: 0,
      monthlyTarget: 300000,
      achieved: 0,
      realizationPct: 0.0,
      week1Achieved: 0,
      week1Quota: 75000,
      week2Achieved: 0,
      week2Quota: 75000,
      week3Achieved: 0,
      week3Quota: 75000,
      week4Achieved: 0,
      week4Quota: 75000
    }
  ];

  // Recent Audit Stream (Exact match to Screenshot 2)
  const sampleActivities = [
    {
      id: 'ACT-01',
      user: 'Alexander Wright',
      timeText: '25 Sept 2026',
      timestamp: '2026-09-25T09:00:00Z',
      action: 'System Initialized',
      description: 'Career Apex CRM initialized with 32 candidate leads.'
    },
    {
      id: 'ACT-02',
      user: 'Arun Kumar',
      timeText: '25 Sept 2026',
      timestamp: '2026-09-25T11:30:00Z',
      action: 'Lead Enrolled',
      studentId: 'CAPX-1001',
      studentName: 'Aditya Deshmukh',
      description: 'Enrolled lead: Aditya Deshmukh (B.Tech CS, VJTI Mumbai)'
    },
    {
      id: 'ACT-03',
      user: 'Arun Kumar',
      timeText: '25 Sept 2026',
      timestamp: '2026-09-25T14:15:00Z',
      action: 'Stage Changed',
      studentId: 'CAPX-1002',
      studentName: 'Harish Nambiar',
      description: 'Changed stage for Harish Nambiar to Converted (Placed)'
    },
    {
      id: 'ACT-04',
      user: 'Arun Kumar',
      timeText: '25 Sept 2026',
      timestamp: '2026-09-25T16:00:00Z',
      action: 'Follow-up Completed',
      studentId: 'CAPX-1002',
      studentName: 'Harish Nambiar',
      description: 'Completed placement follow-up for Harish Nambiar'
    },
    {
      id: 'ACT-05',
      user: 'Rajesh Sharma',
      timeText: '5d ago',
      timestamp: '2026-09-30T10:45:00Z',
      action: 'Lead Assigned',
      studentId: 'CAPX-1014',
      studentName: 'Anand Bajpayee',
      description: 'Lead Anand Bajpayee assigned to Arun Kumar by Rajesh Sharma'
    }
  ];

  // Company overall target
  const companyTargets = {
    month: 'October 2026',
    companyTarget: 1240000,
    achievedRevenue: 42000,
    remainingTarget: 1198000,
    realizationRate: '3.4%',
    weeks: [
      { week: 1, target: 310000, achieved: 42000, status: 'In Progress' },
      { week: 2, target: 310000, achieved: 0, status: 'Upcoming' },
      { week: 3, target: 310000, achieved: 0, status: 'Upcoming' },
      { week: 4, target: 310000, achieved: 0, status: 'Upcoming' }
    ]
  };

  const settings = {
    orgName: 'Career Apex',
    subtitle: 'Student Placement & Career Counseling CRM',
    email: 'support@careerapex.com',
    phone: '+91 98765 00000',
    currency: 'INR (₹)',
    defaultPlacementFee: 45000,
    defaultInstallments: 2
  };

  // Persist to localStorage
  StorageService.set(CRM_KEYS.USERS, users);
  StorageService.set(CRM_KEYS.STUDENTS, students);
  StorageService.set(CRM_KEYS.PAYMENTS, payments);
  StorageService.set(CRM_KEYS.FOLLOWUPS, followups);
  StorageService.set(CRM_KEYS.ACTIVITIES, sampleActivities);
  StorageService.set(CRM_KEYS.TARGETS, companyTargets);
  StorageService.set(CRM_KEYS.EMPLOYEE_TARGETS, employeeTargets);
  StorageService.set(CRM_KEYS.SETTINGS, settings);

  // Set default active session to Admin if none exists
  if (!StorageService.get(CRM_KEYS.SESSION)) {
    StorageService.set(CRM_KEYS.SESSION, users[0]);
  }

  console.log('Seed database completed successfully.');
}

// Auto-seed on load if database is empty
if (typeof window !== 'undefined') {
  window.seedDatabase = seedDatabase;
  window.SeedData = {
    init: () => seedDatabase(false),
    reset: () => seedDatabase(true)
  };
  seedDatabase(false);
}
